---

- name: REPOSITORY - Install prerequisites
  apt:
    name: software-properties-common
    state: present
    update_cache: yes
  when: ansible_os_family == 'Debian' and ansible_distribution == 'Ubuntu'

- name: REPOSITORY - Get Icinga2 keys
  apt_key:
    url: https://packages.icinga.com/icinga.key
    state: present
  when: ansible_os_family == 'Debian' and ansible_distribution == 'Ubuntu'

- name: REPOSITORY - Get Icinga2 repository url
  apt_repository:
    repo: "deb https://packages.icinga.com/ubuntu icinga-{{ ansible_distribution_release }} main"
    state: present
  when: ansible_os_family == 'Debian' and ansible_distribution == 'Ubuntu'

- name: REPOSITORY - Install prerequisites
  yum:
    name: epel-release
    state: present
  when: ansible_os_family == 'RedHat' and ansible_distribution == 'CentOS'

- name: REPOSITORY - Get Icinga2 repository url
  yum:
    name: https://packages.icinga.com/epel/icinga-rpm-release-6-latest.noarch.rpm
    state: present
  when: ansible_os_family == 'RedHat' and ansible_distribution == 'CentOS' and ansible_distribution_major_version == '6'

- name: REPOSITORY - Get Icinga2 repository url
  yum:
    name: https://packages.icinga.com/epel/icinga-rpm-release-7-latest.noarch.rpm
    state: present
  when: ansible_os_family == 'RedHat' and ansible_distribution == 'CentOS' and ansible_distribution_major_version > '6'